# Generated by Django 4.2.3 on 2023-08-03 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_alter_customuser_options_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergenre',
            name='genreUser',
            field=models.ManyToManyField(related_name='userChoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
