# Generated by Django 4.2.3 on 2023-08-03 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_alter_usergenre_genreuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergenre',
            name='genreUser',
            field=models.ManyToManyField(blank=True, related_name='userChoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
