# Generated by Django 4.2.3 on 2023-08-03 17:38

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_alter_usergenre_genreuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='osInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('field_name', models.TextField(blank=True, default='')),
                ('field_data', models.TextField(blank=True, default='')),
                ('user', models.ManyToManyField(related_name='userInformation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Additional OS Information',
            },
        ),
    ]
