# Generated by Django 4.2.3 on 2023-08-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_customuser_account_status_customuser_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_supreme',
            field=models.BooleanField(default=False),
        ),
    ]
