# Generated by Django 4.2.3 on 2023-09-18 10:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('title', models.CharField(default='', max_length=299)),
                ('description', models.TextField(default='')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='blogs')),
            ],
            options={
                'verbose_name': "Blog's",
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=199, null=True)),
            ],
            options={
                'verbose_name': "Course Categorie's",
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('course_banner', models.ImageField(upload_to='courses')),
                ('course_title', models.CharField(default='unspecified', max_length=299)),
                ('rating', models.FloatField(blank=True, default=0.0, max_length=3, null=True)),
                ('course_taglines', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None)),
                ('course_overview', models.TextField(default='')),
                ('benifits', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None)),
                ('pricing', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('base_currency', models.CharField(choices=[('inr', 'INR'), ('usd', 'USD')], default='None', max_length=3)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.coursecategory')),
            ],
            options={
                'verbose_name': 'Courses Information',
            },
        ),
        migrations.CreateModel(
            name='Instructer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('instructer_name', models.CharField(default='', max_length=199)),
                ('instructer_profile', models.ImageField(upload_to='instructers')),
                ('instructer_about', models.TextField(default='')),
            ],
            options={
                'verbose_name': "Instructer's",
            },
        ),
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company')),
                ('company_banner', models.ImageField(blank=True, null=True, upload_to='company')),
                ('home_head', models.CharField(default='', max_length=499)),
                ('home_about', models.TextField(default='')),
                ('showcase', models.ManyToManyField(default='', related_name='showcased_courses', to='home.courses')),
            ],
            options={
                'verbose_name': 'Home Page Data',
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='teacher',
            field=models.ManyToManyField(default='', related_name='instructors', to='home.instructer'),
        ),
        migrations.CreateModel(
            name='CourseIncludes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('title', models.CharField(default='', max_length=299)),
                ('icon', models.CharField(blank=True, choices=[('play_circle', 'Play Circle'), ('newspaper', 'Newspaper'), ('cloud_download', 'Cloud Download'), ('all_inclusive', 'Infinity Logo'), ('devices', 'Devices'), ('edit_document', 'Edit Documents'), ('emoji_events', 'Emoji Events')], default='', max_length=49, null=True)),
                ('connected_course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.courses')),
            ],
            options={
                'verbose_name': "Course Include's",
            },
        ),
    ]
